/**
 * VIMEI Knowledge Tracker - System Configuration
 * ================================================
 * 修改這個檔案來設定 PIN 碼、學員名單及 Google Sheets 連結
 * Edit this file to configure PINs, trainees, and Google Sheets connection
 */

const CONFIG = {

  // ----------------------------------------------------------------
  // 模式設定 / Mode Setting
  // true  = Demo 模式（資料存在瀏覽器，用於測試）
  // false = 正式模式（資料存到 Google Sheets，需先完成 SETUP_GUIDE.md 步驟）
  // ----------------------------------------------------------------
  DEMO_MODE: false,

  // ----------------------------------------------------------------
  // Google Apps Script 網址（完成 SETUP_GUIDE.md 步驟後貼入）
  // ----------------------------------------------------------------
  APPS_SCRIPT_URL: 'https://script.google.com/macros/s/AKfycbxGO8qhJGBMmDueIkz-lse9c3PKsr7lGDdItToojUi-zUozIl6ogt-J-KmGkxKlzbe1Eg/exec',

  // ----------------------------------------------------------------
  // 密碼設定 / PIN & Access Codes (請自行修改 / Please change these)
  // ----------------------------------------------------------------
  ADMIN_PIN: '0000',      // 計畫導師 (Mentor) 密碼
  GUEST_CODE: 'vimei2026', // 輪調主管/同仁 (Assessor) 授權代碼
  EXECUTIVE_CODE: 'vimeivip',  // 高階決策主管 (Executive) 授權代碼

  // ----------------------------------------------------------------
  // UI 設定 / UI Settings
  // ----------------------------------------------------------------
  DEFAULT_LANG:  'en',    // 'en' or 'zh'
  DEFAULT_THEME: 'light', // 'light' or 'dark',

  // ----------------------------------------------------------------
  // 管理者資訊 / Admin Info
  // ----------------------------------------------------------------
  ADMIN: {
    id: 'admin',
    name: 'Mentor',
    avatar: '🧑‍🏫',
    bio: ''
  },

  // ----------------------------------------------------------------
  // 國際生名單與個人 PIN / Trainees & Individual PINs
  // ----------------------------------------------------------------
  TRAINEES: [
    {
      id: 'diane',
      name: '白妙儀 (Diane Solomon Barcelenia)',
      avatar: '<i class="fas fa-user-circle"></i>',
      pin: '1111',
      bio: ''
    },
    {
      id: 'mark',
      name: '段亦林 (Mark Jayzon Comon Dagala)',
      avatar: '<i class="fas fa-user-circle"></i>',
      pin: '2222',
      bio: ''
    },
    {
      id: 'jairuz',
      name: '侯俊材 (Jairuz Delos Reyes Nazareno)',
      avatar: '<i class="fas fa-user-circle"></i>',
      pin: '3333',
      bio: ''
    }
  ],

  // ----------------------------------------------------------------
  // 輪調部門 / Rotation Departments
  // ----------------------------------------------------------------
  DEPARTMENTS: {
    // Chimei
    cmf_production: { id: 'cmf_production', name: 'CHIMEI - Manufacturing', nameZh: '奇美 - 生產製造', shortZh: '生產製造', shortEn: 'Mfg', color: '#64748b', icon: '', pin: '1001' },
    cmf_qc: { id: 'cmf_qc', name: 'CHIMEI - QA/QC', nameZh: '奇美 - 品管', shortZh: '品管', shortEn: 'QA/QC', color: '#64748b', icon: '', pin: '1002' },
    cmf_rd_chinese: { id: 'cmf_rd_chinese', name: 'CHIMEI - R&D (Chinese Dim Sum)', nameZh: '奇美 - 研發 (中點)', shortZh: '研發中', shortEn: 'R&D(C)', color: '#64748b', icon: '', pin: '1003' },
    cmf_rd_western: { id: 'cmf_rd_western', name: 'CHIMEI - R&D (Western Pastry)', nameZh: '奇美 - 研發 (西點)', shortZh: '研發西', shortEn: 'R&D(W)', color: '#64748b', icon: '', pin: '1004' },
    // Yushan
    yushan_qc: { id: 'yushan_qc', name: 'YUSHAN - QA/QC', nameZh: '玉膳 - 品管', shortZh: '玉膳品管', shortEn: 'YS QA', color: '#ea580c', icon: '', pin: '2001' },
    yushan_prep: { id: 'yushan_prep', name: 'YUSHAN - Pre-processing', nameZh: '玉膳 - 前處理段', shortZh: '前處理', shortEn: 'Prep', color: '#ea580c', icon: '', pin: '2002' },
    yushan_cooking: { id: 'yushan_cooking', name: 'YUSHAN - Cooking', nameZh: '玉膳 - 烹煮段', shortZh: '烹煮段', shortEn: 'Cook', color: '#ea580c', icon: '', pin: '2003' },
    yushan_packaging: { id: 'yushan_packaging', name: 'YUSHAN - Packaging', nameZh: '玉膳 - 包裝段', shortZh: '包裝段', shortEn: 'Pkg', color: '#ea580c', icon: '', pin: '2004' },
    yushan_warehouse: { id: 'yushan_warehouse', name: 'YUSHAN - Warehouse & Cold Storage', nameZh: '玉膳 - 倉儲物流與凍庫管理', shortZh: '倉儲', shortEn: 'Whse', color: '#ea580c', icon: '', pin: '2005' },
    // Other (Records)
    holiday: { id: 'holiday', name: 'Day Off / Company Trip', nameZh: '休假日 / 員工旅遊', shortZh: '休假', shortEn: 'Off', color: '#10b981', icon: '', isRecordOnly: true }
  },

  // ----------------------------------------------------------------
  // 初始排程（Demo 模式使用）
  // ----------------------------------------------------------------
  DEFAULT_SCHEDULES: {
    diane: {
      '2026-06-15': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-16': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-17': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-18': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-19': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-22': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-23': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-24': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-25': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-06-26': { dept: 'cmf_production', objective: '調理單位執行燒賣調理配餡 / Siomai Filling Preparation' },
      '2026-07-27': { dept: 'cmf_rd_chinese', objective: '研發中點 新品開發流程/ 認識原料 RD(chinese) New Product Development Process & Ingredient Knowledge' },
      '2026-07-28': { dept: 'cmf_rd_chinese', objective: '研發中點 手工/工程 樣品打樣 RD(chinese)Manual & Pilot Sample Production' },
      '2026-07-29': { dept: 'cmf_rd_western', objective: '西點研發 手工/工程 樣品打樣 RD(western) Manual & Pilot Sample Production' },
      '2026-07-30': { dept: 'cmf_rd_chinese', objective: '研發中點 手工/工程 樣品打樣 RD(chinese)Manual & Pilot Sample Production' },
      '2026-07-31': { dept: 'cmf_rd_western', objective: '西點研發 手工/工程樣品打樣｜測試包餡 RD(western)Manual & Pilot Sample Production, encrusting trial' },
      '2026-08-04': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-05': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-06': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-07': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-10': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-11': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-12': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-13': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-14': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-17': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-18': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-19': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-20': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-21': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-24': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-25': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-26': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-27': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-28': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-08-31': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-09-01': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-02': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-03': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-04': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-07': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-08': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-09': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-10': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-11': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-14': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-15': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-16': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-17': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-18': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-21': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-22': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-23': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-24': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-25': { dept: 'holiday', objective: '中秋節 (Mid-Autumn Festival)' },
      '2026-09-28': { dept: 'holiday', objective: '教師節 (Teacher's Day)' },
      '2026-09-29': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-30': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-10-01': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-02': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-05': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-06': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-07': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-08': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-09': { dept: 'holiday', objective: '雙十節補假 (Double Tenth Day Compensated Holiday)' },
      '2026-10-25': { dept: 'holiday', objective: '光復節 (Retrocession Day)' },
      '2026-10-12': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-13': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-14': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-15': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-16': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-19': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-20': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-21': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-22': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-23': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-26': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-27': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-28': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-29': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-30': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-11-02': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-03': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-04': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-05': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-06': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-09': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-10': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-11': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-12': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-13': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-16': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-17': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-18': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-19': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-20': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-23': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-24': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-25': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-26': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-27': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-30': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-12-01': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-02': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-03': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-04': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-07': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-08': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-09': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-10': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-11': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-14': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-15': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-16': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-17': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-18': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-21': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-22': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-23': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-24': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-25': { dept: 'holiday', objective: '行憲紀念日 (Constitution Day)' },
      '2026-12-28': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-29': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-30': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-31': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
    },
    mark: {
      '2026-06-01': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-02': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-03': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-04': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-05': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-08': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-09': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-10': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-11': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-12': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-29': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-06-30': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-01': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-02': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-03': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-06': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-07': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-08': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-09': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-10': { dept: 'cmf_production', objective: '成型蒸炊單位執行設備拆洗 / Equipment Disassembly & Cleaning' },
      '2026-07-27': { dept: 'cmf_rd_chinese', objective: '研發中點 新品開發流程/ 認識原料 RD(chinese) New Product Development Process & Ingredient Knowledge' },
      '2026-07-28': { dept: 'cmf_rd_chinese', objective: '研發中點 手工/工程 樣品打樣 RD(chinese)Manual & Pilot Sample Production' },
      '2026-07-29': { dept: 'cmf_rd_chinese', objective: '研發中點 手工/工程 樣品打樣 RD(chinese)Manual & Pilot Sample Production' },
      '2026-07-30': { dept: 'cmf_rd_western', objective: '西點研發 手工/工程 樣品打樣 RD(western) Manual & Pilot Sample Production' },
      '2026-07-31': { dept: 'cmf_rd_chinese', objective: '研發中點 手工/工程 樣品打樣 RD(chinese)Manual & Pilot Sample Production' },
      '2026-08-04': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-05': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-06': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-07': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-10': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-11': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-12': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-13': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-14': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-17': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-18': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-19': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-20': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-21': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-24': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-25': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-26': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-27': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-28': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-08-31': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-09-01': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-02': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-03': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-04': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-07': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-08': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-09': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-10': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-11': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-14': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-15': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-16': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-17': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-18': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-21': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-22': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-23': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-24': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-25': { dept: 'holiday', objective: '中秋節 (Mid-Autumn Festival)' },
      '2026-09-28': { dept: 'holiday', objective: '教師節 (Teacher's Day)' },
      '2026-09-29': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-09-30': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-10-01': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-02': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-05': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-06': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-07': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-08': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-09': { dept: 'holiday', objective: '雙十節補假 (Double Tenth Day Compensated Holiday)' },
      '2026-10-25': { dept: 'holiday', objective: '光復節 (Retrocession Day)' },
      '2026-10-12': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-13': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-14': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-15': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-16': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-19': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-20': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-21': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-22': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-23': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-26': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-27': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-28': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-29': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-10-30': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-11-02': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-03': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-04': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-05': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-06': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-09': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-10': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-11': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-12': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-13': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-16': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-17': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-18': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-19': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-20': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-23': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-24': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-25': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-26': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-27': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-11-30': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-12-01': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-02': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-03': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-04': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-07': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-08': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-09': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-10': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-11': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-14': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-15': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-16': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-17': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-18': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-21': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-22': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-23': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-24': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-25': { dept: 'holiday', objective: '行憲紀念日 (Constitution Day)' },
      '2026-12-28': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-29': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-30': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-12-31': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
    },
    jairuz: {
      '2026-06-01': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-02': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-03': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-04': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-05': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-08': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-09': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-10': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-11': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-12': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-15': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-16': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-17': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-18': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-19': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-22': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-23': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-24': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-25': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-26': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-29': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-06-30': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-01': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-02': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-03': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-06': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-07': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-08': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-09': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-10': { dept: 'cmf_production', objective: '西點單位執行550成型篩選/封口 / Model 550 Forming / Inspection / Sealing' },
      '2026-07-27': { dept: 'cmf_rd_chinese', objective: '研發中點 新品開發流程/ 認識原料 RD(chinese) New Product Development Process & Ingredient Knowledge' },
      '2026-07-28': { dept: 'cmf_rd_western', objective: '西點研發 手工/工程 樣品打樣 RD(western) Manual & Pilot Sample Production' },
      '2026-07-29': { dept: 'cmf_rd_chinese', objective: '研發中點 手工/工程 樣品打樣 RD(chinese)Manual & Pilot Sample Production' },
      '2026-07-30': { dept: 'cmf_rd_western', objective: '西點研發 手工/工程 樣品打樣 RD(western) Manual & Pilot Sample Production' },
      '2026-07-31': { dept: 'cmf_rd_western', objective: '西點研發 手工/工程樣品打樣｜測試包餡 RD(western)Manual & Pilot Sample Production, encrusting trial' },
      '2026-08-04': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-05': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-06': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-07': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-10': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-11': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-12': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-13': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-14': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-17': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-18': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-19': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-20': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-21': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-24': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-25': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-26': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-27': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-28': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-08-31': { dept: 'yushan_packaging', objective: '玉膳(調理食品：後段包裝) Prepared Foods – Packaging Area' },
      '2026-09-01': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-02': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-03': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-04': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-07': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-08': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-09': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-10': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-11': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-14': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-15': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-16': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-17': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-18': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-21': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-22': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-23': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-24': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-25': { dept: 'holiday', objective: '中秋節 (Mid-Autumn Festival)' },
      '2026-09-28': { dept: 'holiday', objective: '教師節 (Teacher's Day)' },
      '2026-09-29': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-09-30': { dept: 'yushan_warehouse', objective: '玉膳(倉儲物流與凍庫管理) Warehouse & Cold Storage Management' },
      '2026-10-01': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-02': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-05': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-06': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-07': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-08': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-09': { dept: 'holiday', objective: '雙十節補假 (Double Tenth Day Compensated Holiday)' },
      '2026-10-25': { dept: 'holiday', objective: '光復節 (Retrocession Day)' },
      '2026-10-12': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-13': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-14': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-15': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-16': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-19': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-20': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-21': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-22': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-23': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-26': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-27': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-28': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-29': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-10-30': { dept: 'yushan_qc', objective: '玉膳(現場品管 QA/QC) On-site QA/QC' },
      '2026-11-02': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-03': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-04': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-05': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-06': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-09': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-10': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-11': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-12': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-13': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-16': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-17': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-18': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-19': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-20': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-23': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-24': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-25': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-26': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-27': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-11-30': { dept: 'yushan_prep', objective: '玉膳(調理食品：前處理段) Prepared Foods – Pre-processing' },
      '2026-12-01': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-02': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-03': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-04': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-07': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-08': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-09': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-10': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-11': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-14': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-15': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-16': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-17': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-18': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-21': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-22': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-23': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-24': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-25': { dept: 'holiday', objective: '行憲紀念日 (Constitution Day)' },
      '2026-12-28': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-29': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-30': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
      '2026-12-31': { dept: 'yushan_cooking', objective: '玉膳(調理食品：烹煮區) Prepared Foods – Cooking Area' },
    }
  }


};
